CREATE DATABASE programate;
USE programate;

CREATE TABLE nav(
	id_nav INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	type INT(1) NOT NULL, /*1: navegacion, 2: company name, 3: button dark*/
	route VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE footer(
	id_footer INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE footer_item(
	id_footer_item INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_footer INT NOT NULL REFERENCES footer(id_footer),
	name VARCHAR(200) NOT NULL,
	route VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE users(
	id_user INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(200) NOT NULL,
	last_name VARCHAR(200) NOT NULL,
	username VARCHAR(200) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(200) NOT NULL UNIQUE,
	phone VARCHAR(200) NOT NULL,
	address TEXT NOT NULL,
	avatar VARCHAR(255) NOT NULL,
    sexo INT(1) NOT NULL,
    status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE token(
	id_token INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_user INT NOT NULL REFERENCES user(id_user),
	email VARCHAR(200) NOT NULL,
    token VARCHAR(255) NOT NULL,
	status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE home(
	id_home INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
	route VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
	status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE presentation(
	id_presentation INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    date VARCHAR(100) NOT NULL,
	route VARCHAR(100) NOT NULL,
    thumbnail VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    free INT(1) NOT NULL,
	status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE courses(
	id_course INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
	date VARCHAR(100) NOT NULL,
    route VARCHAR(100) NOT NULL,
    thumbnail VARCHAR(255) NOT NULL,
    description VARCHAR(200) NOT NULL,
    free INT(1) NOT NULL,
	status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE content_courses(
	id_content_course INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    id_course INT UNSIGNED NOT NULL,
	name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
	status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_course) REFERENCES courses(id_course) 
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE content_courses_items(
	id_content_courses_items INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    id_content_course INT UNSIGNED NOT NULL,
	name VARCHAR(100) NOT NULL,
    time VARCHAR(100) NOT NULL,
    video VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    free INT(1) NOT NULL,
	status INT(1) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_content_course) REFERENCES content_courses(id_content_course) 
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;